version: "3"
services:
    app:
        build:
            context: .
        container_name: kabukeisan
        ports:
            - "3001:3000"
        volumes:
            - ./:/app
        tty: true
