export const CHECKSTOCKCONTENT = [
    {
        label: "1、その企業は、少なくとも数年は収益が増え続けることを可能にする、十分な市場可能性のある製品やサービスをもっているか?",
        value1: "1",
        value2: "2",
        value3: "3",
        value4: "4",
        value5: "5",
        registerName: "question-1",
    },
    {
        label: "2、現在売れている製品ラインの潜在的な需要がほとんどなくなったときに、経営陣には会社の収益をさらに伸ばすような製品やプロセスを開発・発展し続ける決意があるか?",
        value1: "1",
        value2: "2",
        value3: "3",
        value4: "4",
        value5: "5",
        registerName: "question-2",
    },
    {
        label: "3、企業の規模と比べて、どのくらい企業のリサーチと開発努力が効果的であるか?",
        value1: "1",
        value2: "2",
        value3: "3",
        value4: "4",
        value5: "5",
        registerName: "question-3",
    },
    {
        label: "4、その企業は、平均以上の販売組織があるか?",
        value1: "1",
        value2: "2",
        value3: "3",
        value4: "4",
        value5: "5",
        registerName: "question-4",
    },
    {
        label: "5、その企業には、十分な利幅があるか?",
        value1: "1",
        value2: "2",
        value3: "3",
        value4: "4",
        value5: "5",
        registerName: "question-5",
    },
    {
        label: "6、利幅を改善、または維持するために何をしているか?",
        value1: "1",
        value2: "2",
        value3: "3",
        value4: "4",
        value5: "5",
        registerName: "question-6",
    },
    {
        label: "7、その企業には、労働者・従業員との関係に特筆すべき点があるか?",
        value1: "1",
        value2: "2",
        value3: "3",
        value4: "4",
        value5: "5",
        registerName: "question-7",
    },
    {
        label: "8、その企業には、企業幹部との関係に特筆すべき点があるか?",
        value1: "1",
        value2: "2",
        value3: "3",
        value4: "4",
        value5: "5",
        registerName: "question-8",
    },
    {
        label: "9、その企業は、マネージメントに柔軟性があるか?",
        value1: "1",
        value2: "2",
        value3: "3",
        value4: "4",
        value5: "5",
        registerName: "question-9",
    },
    {
        label: "10、企業の費用分析と会計管理は、どのくらいきちんとしているか?",
        value1: "1",
        value2: "2",
        value3: "3",
        value4: "4",
        value5: "5",
        registerName: "question-10",
    },
    {
        label: "11、競争相手と比べて、どのぐらいその企業が突出しているかを知る手がかりとなるような、その分野特有の評価できる特徴がなにかあるか?",
        value1: "1",
        value2: "2",
        value3: "3",
        value4: "4",
        value5: "5",
        registerName: "question-11",
    },
    {
        label: "12、利益という点で、短期間および長期間の見通しがその企業にあるか?",
        value1: "1",
        value2: "2",
        value3: "3",
        value4: "4",
        value5: "5",
        registerName: "question-12",
    },
    {
        label: "13、予測可能な未来に、企業の成長が著しいために自己資金調達が行われ、その結果株式の総数が増大し、現在の株主が予期していた利益が、ほとんど相殺されてしまうような事態になりそうか?",
        value1: "1",
        value2: "2",
        value3: "3",
        value4: "4",
        value5: "5",
        registerName: "question-13",
    },
    {
        label: "14、その企業の経営陣は、物事がうまくいっている時には、さまざまな出来事を投資家にどんどん話すのに、問題や損失が生じると、だんまりを決め込んでしまうようなことがあるか?",
        value1: "1",
        value2: "2",
        value3: "3",
        value4: "4",
        value5: "5",
        registerName: "question-14",
    },
    {
        label: "15、その企業は、完璧な経営体制を敷いているか他の企業よりも先に製品を開発しているか",
        value1: "1",
        value2: "2",
        value3: "3",
        value4: "4",
        value5: "5",
        registerName: "question-15",
    },
];
