name: Build React on S3
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - name: Checkout
              uses: actions/checkout@main # リポジトリをチェックアウト

            - name: Install Dependencies
              run: yarn && echo $AWS_ACCESS_KEY_ID

            - name: Build
              run: yarn run build # React ビルド

            - name: Deploy # S3にデプロイ
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  # S3のbucket-for-deploying-react-projectバケットにデプロイ
              run: echo $AWS_ACCESS_KEY_ID
              # run: |
              #     aws s3 cp --recursive --region ap-northeast-1 build s3://kabukeisan-fe
